name: pr

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
      - wheel-build-pylibraft
      - wheel-build-raft-dask
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@branch-24.12
    if: always()
    with:
      needs: ${{ toJSON(needs) }}
  wheel-build-pylibraft:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-24.12
    with:
      build_type: pull-request
      script: ci/build_wheel_pylibraft.sh
  wheel-build-raft-dask:
    needs: wheel-build-pylibraft
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-24.12
    with:
      build_type: pull-request
      script: "ci/build_wheel_raft_dask.sh"
